project:
  type: website

website:
  title: Repositorio de Tesis Venezolanas en Ecología
  site-url: https://svecologia.github.io/repositorio-tesis/
  description: "Este repositorio es una iniciativa comunitaria del Comité Editorial de Ecotrópicos para crear respaldos accesibles y abiertos de los trabajos de grado en ecología y adyacentes.

"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tesis.qmd
        text: Tesis
      - href: about.qmd
        text: Acerca de
      - icon: rss
        href: tesis.xml

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



